package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.22

import (
	"context"
	"fmt"

	"github.com/watariRyo/go-graphql/graph/model"
)

// Department is the resolver for the department field.
func (r *employeeResolver) Department(ctx context.Context, obj *model.Employee) (*model.Department, error) {
	panic(fmt.Errorf("not implemented: Department - department"))
}

// Company is the resolver for the company field.
func (r *employeeResolver) Company(ctx context.Context, obj *model.Employee) (*model.Company, error) {
	//panic(fmt.Errorf("not implemented: Company - company"))
	return r.CompanyLoader.Load(obj.CompanyID)
}

// Employee returns EmployeeResolver implementation.
func (r *Resolver) Employee() EmployeeResolver { return &employeeResolver{r} }

type employeeResolver struct{ *Resolver }
